export const States = {
    "AL": "Alabama", "AK": "Alaska", "AS": "American Samoa", "AZ": "Arizona", "AR": "Arkansas", "CA": "California", "CO": "Colorado", "CT": "Connecticut", "DE": "Delaware", "DC": "District Of Columbia", "FM": "Federated States Of Micronesia", "FL": "Florida", "GA": "Georgia", "GU": "Guam", "HI": "Hawaii", "ID": "Idaho", "IL": "Illinois", "IN": "Indiana", "IA": "Iowa",
    "KS": "Kansas", "KY": "Kentucky", "LA": "Louisiana", "ME": "Maine", "MH": "Marshall Islands", "MD": "Maryland", "MA": "Massachusetts", "MI": "Michigan", "MN": "Minnesota", "MS": "Mississippi",
    "MO": "Missouri", "MT": "Montana", "NE": "Nebraska", "NV": "Nevada", "NH": "New Hampshire", "NJ": "New Jersey", "NM": "New Mexico", "NY": "New York", "NC": "North Carolina", "ND": "North Dakota", "MP": "Northern Mariana Islands", "OH": "Ohio", "OK": "Oklahoma", "OR": "Oregon", "PW": "Palau", "PA": "Pennsylvania", "PR": "Puerto Rico", "RI": "Rhode Island", "SC": "South Carolina", "SD": "South Dakota", "TN": "Tennessee", "TX": "Texas", "UT": "Utah", "VT": "Vermont", "VI": "Virgin Islands", "VA": "Virginia", "WA": "Washington", "WV": "West Virginia", "WI": "Wisconsin", "WY": "Wyoming"
}

export const randomcategoris1 = [
    'Agriculture',
    'Banking and Accounting',
    'Call Centers',
    'Chemical',
    'Technology',
    'Education',
    'Food and Beverage',
    'Non Profit',
    'Manufacturing',
    'Construction',
    'Computer Networks',
    'Internet',
    'GIS & GPS',
    'Audio-Visual',
    'CCTV',
    'IT, Information Technology',
    'IT Software Programming',
    'Website Design',
    'Computer Hardware',
    'Database Backup',
    'Computer Network Security',
    'Janitorial & Custodial Services',
    'Janitorial & Custodial Supplies',
    'Waste Removal & Recycling',
    'Building Maintenance',
    'Food Services',
    'Food Supply',
    'Food Equipment',
    'Facility & Equipment',
    'Office Equipment',
];

export const randomcategoris2 = [
    'Property Management',
    'Laundry & Dry Cleaning',
    'Landscaping',
    'Landscape Architecture',
    'Tree Trimming',
    'Irrigation',
    'Snow Plow & Snow Removal',
    'Lawn Care & Landscaping',
    'Medical, Healthcare',
    'Medical Staffing',
    'Medical Billing',
    'Medical Equipment',
    'Dentistry',
    'Mental Health',
    'Pharmacy',
    'Laboratory Drug Testing',
    'Medical Supplies',
    'Ambulance',
    'Employment Staffing',
    'Insurance & workers compensation',
    'Travel Management',
    'Human Resources & Payroll',
    'Time and Attendance',
    'Quality Control',
    'Manufacturing',
    'Automatic Vehicle Location',
    'Packing Supplies',
    'Metal Fabrication & Welding',
    'Plastics',
    'Facilities Leasing',
];

export const randomcategoris3 = [
    'Social Services',
    'Printing & Binding',
    'Transcription',
    'Court Reporting',
    'Appraisal',
    'Document Management',
    'Document Shredding',
    'Debt Collection & Accounts',
    'Parking & Valet Services',
    'Management & Leadership Consulting',
    'Legal Services',
    'Auctioning & Liquidation',
    'Cultural Resources',
    'Mass Notification',
    'Financial Investment',
    'Accounting & Audit',
    'Lobbying and Public Affairs',
    'Administrative & Secretary',
    'Data Processing',
    'Security & Safety',
    'Security Guard',
    'Background Checks',
    'Security System',
    'Fire Fighting & Rescue',
    'Weapons & Ammunition',
    'Police Equipment',
    'Equipment Rental',
    'Facility Management',
    'Shipping & Warehousing',
    'Food',
];

export const randomcategoris4 = [
    'Disaster Recovery',
    'Canine',
    'Biometrics & Fingerprint',
    'Identification Smart Cards',
    'Architecture',
    'Land Architect',
    'Design Build',
    'Civil Engineer',
    'Surveying',
    'Mapping & GIS',
    'Utility Location',
    'Agricultural, Environmental',
    'Environmental',
    'Water Purification Treatment',
    'Pest Control',
    'Portable Restroom(Porta Potty)',
    'Transportation, Warehouse',
    'Fleet & Bus',
    'Train & Railroad',
    'Boats & Ferry',
    'Aircraft & Aviation',
    'Courier Services',
    'Freight & Trucking',
    'Transportation',
    'Moving & Relocation',
    'Towing',
    'Clothing & Uniforms',
    'Furniture',
    'Appliances & Electronics'
]